### ISSUE TITLE
Questions about interpreting the proximity effect

### ISSUE THREAD

**Issue by HelloWorldLTY** [sunericd/SpatialAgingClock#1]
Hi, thanks for your great work, which is really exciting and inspiring. I tried the example and had some problems about interpreting outputs. I treid the code

```
df = spatialclock.proximity.compute_proximity_effects(adata, cutoff, celltypes,
                                                      min_pairs=1) # for tutorial only
```

And the output table seems containing many NaN value. Do you have any ideas about the reason? Is it safe to directly filter the nan values? Thanks.
![image](https://github.com/user-attachments/assets/84c69c6b-08dd-4732-b974-9492540976de)

**Comment by sunericd** [comment]
Thanks for the interest! The tutorial dataset is a very small subset of the full dataset -- mostly for tutorial and demonstration purposes. Because of its small size, a lot of cell proximity relationships are not captured and this is particularly true for rare cell types (for example, there are no macrophages near NSCs in the tutorial dataset). This is reflected in the outputs you show above (see last column "Near Num" for the number of proximity relationships detected).

If you want to try out this analysis on the full (or larger) dataset, you can download the publicly available AnnData objects at [https://doi.org/10.5281/zenodo.13883177](https://doi.org/10.5281/zenodo.13883177). Example of proximity effect outputs (using SpaGE imputation) are also available in one of our supplementary tables ([download](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-024-08334-8/MediaObjects/41586_2024_8334_MOESM4_ESM.zip)).

If you are deploying the spatial aging clocks on your own dataset, you may encounter some NaN values depending on the size of the dataset. You can safely filter out these rows from downstream analysis since they are proximity relationships that are not encountered in your dataset. Alternatively, you can try expanding the radius for calling proximity relationships to capture more of them.

Hope this helps with interpreting the outputs!

**Comment by HelloWorldLTY** [comment]
Thank you, that is very extensive. I will try the full dataset.

**Comment by HelloWorldLTY** [comment]
Hi, I have another quick follow-up question. Do we need to train our own model for our own dataset, if so, are there any tutorials for us to run? I also wonder if we impute the input data with other approaches, what keywords we should use in get prediction after imputation. Thanks!

**Comment by sunericd** [comment]
Good questions. I am still developing an automated model builder to be included in this package, but you can already manually build the spatial aging clocks for another dataset using the script from our other Github repo for inspiration (there will need to be a few small changes in key names and paths to fit your dataset): [https://github.com/sunericd/spatial_aging_clocks/tree/master/scripts/train_clocks](https://github.com/sunericd/spatial_aging_clocks/tree/master/scripts/train_clocks)

In particular, I would look at `full_train_clock.py` for building the clock objects that can then be used with this package or the `cv_train_clock.py` to get cross-validated predicted ages (these can be inserted for the proximity effect and other downstream analysis in this package). 

The easiest way to use your own imputation would be to just insert them into `adata.X` (or create a new object with the imputed expression as the counts) and then apply our pipeline afterwards. Only the missing genes are imputed with our in-house methods (mean, spage, etc.) so if they aren't missing in the input data, it will just keep those expressions for the clocks.

**Comment by HelloWorldLTY** [comment]
Sounds nice, thanks a lot!
